name: Java CI with Maven

on:
  push:
    branches: [ "fb_DaryaAndreyuk_14_AllureReportGithubPages" ]
  pull_request:
    branches: [ "fb_DaryaAndreyuk_14_AllureReportGithubPages" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size 2g
        ports:
          - 4444:4444

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Decode Excel file
        shell: pwsh
        run: echo ${{ secrets.EXCEL_BASE64 }} | Out-File -FilePath src/test/resources/data/Sheet.base64

      - name: Convert base64 to Excel
        shell: pwsh
        run: |
          $base64String = Get-Content src/test/resources/data/Sheet.base64
          [System.IO.File]::WriteAllBytes("src/test/resources/data/Sheet.xlsx", [System.Convert]::FromBase64String($base64String))

      - name: Run smoke tests
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: mvn test -Psmoke-tests

      - name: Generate Allure report
        run: |
          allure generate allure-results -o allure-report --clean
        continue-on-error: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          keep_files: false